<div class="container">
	<div class="row mb-3">

		

		<div class="nav-scroller shadow-sm">
			<nav class="nav nav-underline">
				<a href="<?= $this->url('settings', ['action' => 'email']); ?>" class="nav-link">
					Изменить Email
				</a>
				
				<a href="<?= $this->url('settings', ['action' => 'password']); ?>" class="nav-link">
					Изменить пароль
				</a>

			</nav>
		</div>
	</div>
</div>