<?php

$title = 'Удаление События';
#page title
$this->headTitle($this->escapeHtml($title));


$form = $this->form;
$form->setAttribute('action', $this->url('history', ['action' => 'delete', 'id' => $this->quiz->getId()]));
$form->prepare();

?>

<div class="container">

    <div class="row">

        <div class="col-md-5 shadow-sm mx-auto">

            <?= $this->form()->openTag($form); ?>

            <h3 class="pt-2 text-md-center mb-3">
                Удаление События
            </h3>

            <p class="form-text">Вы уверены, что хотите удалить событие?</p>

            <div class="mb-3 float-left">
                <?= $this->formSubmit($form->get('delete_interaction')->setValue('Нет')); ?>
            </div>

            <div class="mb-3 float-right">
                <?= $this->formHidden($form->get('user_id')->setValue($this->authHelper()->getUserId())); ?>

                <?= $this->formHidden($form->get('client_id')->setValue($this->quiz->getId())); ?>

                <?= $this->formSubmit($form->get('delete_interaction')->setValue('Да')); ?>
            </div>

            <?= $this->form()->closeTag(); ?>
        </div>

    </div>

</div>
