<?php

use History\Model\Entity\InteractionsEntity;

$title = $this->translate('История');
#meta keywords
$this->headMeta()->appendName('keywords', 'История');
#meta description
$this->headMeta()->appendName('description', 'List of all clients.');
#page title
$this->headTitle($this->escapeHtml($title));

$typeColors = [
    'Звонок' => '#1E9934',
    'Встреча' => '#FF5733',
    'Email' => '#3357FF',
    'Социальные сети' => '#CCAC00',
    'Другое' => '#DC143C',
];
?>

<div class="container">

    <div class="row">

        <div class="col-md-12">

            <div class="d-block">
                <h3 class="mb-3"><?= $this->translate('История взаимодействия с ') . $this->client->getUsername(); ?></h3>

                <p>
                    <a href="<?= $this->url('history', ['action' => 'create', 'id' => $this->client->getId()]); ?>" class="btn btn-sm btn-primary">
                        <i>+</i> Добавить
                    </a>
                </p>

            </div>


            <form method="get" action="/history/index" >
                <div class="mb-3">
                    <div class="input-group">
                        <input type="text" name="s" required="required" size="40" maxlength="255" class="form-control" placeholder="Введите текст запроса" data-toggle="tooltip" title="Введите текст запроса" value="">
                    </div>
                </div>
                <div class="mb-3 float-right">
                    <input type="submit" name="search_history" class="btn btn-primary" value="Поиск">
                </div>
            </form>

            <?= $this->form()->closeTag() ?>

            <?php if(count($this->interactions) > 0): ?>

                <div class="table-responsive">

                    <table class="table table-striped table-sm">

                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Дата события</th>
                            <th>Тип событие</th>
                            <th>Пояснение</th>
                            <th>Ответственный</th>
                            <th>Действия</th>
                        </tr>
                        </thead>

                        <tbody>

                        <?php /**
                        * @var InteractionsEntity $interaction
                        */
                        ?>
                        <?php foreach($this->interactions as $interaction): ?>
                            <?php if($interaction->getStatus() == '1'): ?>
                                <tr>
                                    <td><?= $interaction->getId(); ?></td>
                                    <td><?=
                                        $this->dateFormat(
                                            new DateTime($interaction->getInteractionDate()),
                                            IntlDateFormatter::SHORT ,
                                            IntlDateFormatter::NONE,
                                            "ru_RU"
                                        );
                                        ?>
                                    </td>
                                    <td style="color: <?= $typeColors[$interaction->getTypeName()] ?? 'black'; ?>">
                                        <?= $interaction->getTypeName(); ?>
                                    </td>
                                    <td><?= $interaction->getNotes(); ?></td>
                                    <td><?= $interaction->getUsername(); ?></td>

                                    <td>
                                        <!--a href="<?= $this->url('history', ['action' => 'view', 'id' => $interaction->getId()]); ?>">
											Просмотреть
										</a-->
                                        <!--a href="<?= $this->url('history', ['action' => 'edit', 'id' => $interaction->getId()]); ?>">
											Редактировать
										</a-->
                                        <a href="<?= $this->url('history', ['action' => 'delete', 'id' => $interaction->getId()]); ?>">
                                            Удалить
                                        </a>

                                    </td>
                                </tr>
                            <?php endif; ?>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            <?php else: ?>
                <p class="form-text text-muted pt-1">
                    Нет записей</p>
                </p>
            <?php endif; ?>
        </div>
    </div>
</div>
