<?php

$title = $this->translate('Новый клиент');
#meta keywords
$this->headMeta()->appendName('keywords', 'Create, Start, New');
#meta description
$this->headMeta()->appendName('description', 'Добавить клиента');
#page title
$this->headTitle($this->escapeHtml($title));


$form = $this->form;
$form->setAttribute('action', $this->url('crm', ['action' => 'create']));
$form->prepare();

?>

<div class="container">

	<div class="row">

		<div class="col-md-6 shadow-sm mx-auto">

			<?= $this->form()->openTag($form); ?>

			<h3 class="pt-2 text-md-center">
				<?= $this->translate('Добавить клиента'); ?>
			</h3>

			<div class="mb-3">
				<?= $this->formLabel($form->get('username')); ?>
				<div class="input-group">
					<?= $this->formText($form->get('username')); ?>
				</div>
				<div class="text-danger">
					<?= $this->formElementErrors($form->get('username')); ?>
				</div>
			</div>

            <div class="mb-3">
                <?= $this->formLabel($form->get('pasport')); ?>
                <div class="input-group">
                    <?= $this->formText($form->get('pasport')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('pasport')); ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formLabel($form->get('birthday')); ?>
                <div class="input-group">
                    <?= $this->formDate($form->get('birthday')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('birthday')); ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formLabel($form->get('nomber_d')); ?>
                <div class="input-group">
                    <?= $this->formText($form->get('nomber_d')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('nomber_d')); ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formLabel($form->get('data_d')); ?>
                <div class="input-group">
                    <?= $this->formDate($form->get('data_d')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('data_d')); ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formLabel($form->get('trafic')); ?>
                <div class="input-group">
                    <?= $this->formSelect($form->get('trafic')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('trafic')); ?>
                </div>
            </div>

            <div class="mb-3">
                <?= $this->formLabel($form->get('coments')); ?>
                <div class="input-group">
                    <?= $this->formTextarea($form->get('coments')); ?>
                </div>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('coments')); ?>
                </div>
            </div>

			<div class="mb-3 float-right">

				<?= $this->formSubmit($form->get('create_client')); ?>
			</div>

			<?= $this->form()->closeTag(); ?>
		</div>

	</div>

</div>


