<?php

$title = $this->translate('Все клиенты');
#meta keywords
$this->headMeta()->appendName('keywords', 'Клиенты');
#meta description
$this->headMeta()->appendName('description', 'List of all clients.');
#page title
$this->headTitle($this->escapeHtml($title));

?>

<div class="container">

	<div class="row">

		<div class="col-md-12">

			<div class="d-block">
				<h3 class="mb-3"><?= $this->translate('Все клиенты'); ?></h3>

				<p>
				<a href="<?= $this->url('crm', ['action' => 'create']); ?>" class="btn btn-sm btn-primary">
					<i>+</i> Добавить нового клиента
				</a>
				</p>

			</div>


            <form method="get" action="/crm/index" >
                <div class="mb-3">
                    <div class="input-group">
                        <input type="text" name="s" required="required" size="40" maxlength="255" class="form-control" placeholder="Введите номер паспорта для поиска" data-toggle="tooltip" title="Введите номер паспорта" value="">
                    </div>
                </div>
                <div class="mb-3 float-right">
                    <input type="submit" name="create_client" class="btn btn-primary" value="Поиск">
                </div>
            </form>

            <?php
            $formPassport = $this->formPassport;
            $formPassport->prepare(); // The correct enctype is set here
            $fileElement = $formPassport->get('image-file');
            echo $this->form()->openTag($formPassport);
            ?>

            <div class="form-element">
                <?= $this->formLabel($fileElement) ?>
                <?= $this->formFile($fileElement) ?>
                <?= $this->formElementErrors($fileElement) ?>
            </div>

            <button>Загрузить</button>

            <?= $this->form()->closeTag() ?>

			<?php if(count($this->clients) > 0): ?>

				<div class="table-responsive">
					
					<table class="table table-striped table-sm">
						
						<thead>
							<tr>
								<th>#</th>
								<th>ФИО</th>
								<th>Паспорт</th>
								<th>Дата рождения</th>
								<th>Номер договора</th>
								<th>Дата договора</th>
								<th>Тариф</th>
								<th>Комментарий</th>
                                <th>Статус</th>
                                <th>Дата добавления</th>
								<th>Действия</th>
							</tr>
						</thead>

						<tbody>
							
							<?php foreach($this->clients as $client): ?>
								<?php if($client->getStatus() == '1'): ?>
								<tr>
									<td><?= $client->getId(); ?></td>
									<td>

											<?= $client->getUsername(); ?>
											
									</td>
									<td><?= $client->getPasport(); ?></td>
									<td><?=
                                        $this->dateFormat(
                                            new DateTime($client->getBirthday()),
                                            IntlDateFormatter::SHORT ,
                                            IntlDateFormatter::NONE,
                                            "ru_RU"
                                        );
                                        ?></td>
									<td>

									<?= $client->getNomberD(); ?>
											
									</td>
									<td><?=
                                        $this->dateFormat(
                                            new DateTime($client->getDataD()),
                                            IntlDateFormatter::SHORT ,
                                            IntlDateFormatter::NONE,
                                            "ru_RU"
                                        );
                                        ?></td>
																			<td>
									<?php
                                    switch ($client->getTrafic()) {
                                        case 'Base':
                                            echo "Базовый";
                                            break;
                                        case 'Family':
                                            echo "Семейный";
                                            break;
                                    } ?>
									</td>
									<td>
									<?= $client->getComents(); ?>
									</td>
									<td>
										Активен
									</td>
									<td><?=
                                        $this->dateFormat(
                                            new DateTime($client->getDataAd()),
                                            IntlDateFormatter::SHORT ,
                                            IntlDateFormatter::NONE,
                                            "ru_RU"
                                        );
                                        ?></td>
									<td>
										<!--a href="<?= $this->url('crm', ['action' => 'view', 'id' => $client->getId()]); ?>">
											Просмотреть
										</a-->
										<!--a href="<?= $this->url('crm', ['action' => 'edit', 'id' => $client->getId()]); ?>">
											Редактировать
										</a-->
										<a href="<?= $this->url('crm', ['action' => 'delete', 'id' => $client->getId()]); ?>">
											Удалить
										</a>

									</td>
								</tr>
								<?php endif; ?>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
			<?php else: ?>
			<p class="form-text text-muted pt-1">
				Нет записей</p>
			</p>
			<?php endif; ?>
	   </div>
	</div>
</div>
